version: "3.7"
services:
  ddns-updater:
    image: ddns-updater-sh 
    container_name: ddns-updater
    entrypoint: /config/data/replace_config_tokens.sh 
    network_mode: bridge
    ports:
      - 8888:8000/tcp
    volumes:
      - ./data:/config/data
    environment:
      - PERIOD=5m
      - UPDATE_COOLDOWN_PERIOD=5m
      - PUBLICIP_FETCHERS=all
      - PUBLICIP_HTTP_PROVIDERS=all
      - PUBLICIPV4_HTTP_PROVIDERS=all
      - PUBLICIPV6_HTTP_PROVIDERS=all
      - PUBLICIP_DNS_PROVIDERS=all
      - PUBLICIP_DNS_TIMEOUT=3s
      - HTTP_TIMEOUT=10s
      - RESOLVER_ADDRESS=1.1.1.1:53
      # Web UI
      - LISTENING_ADDRESS=:8888
      - ROOT_URL=/

      # Backup
      - BACKUP_PERIOD=0 # 0 to disable
      - BACKUP_DIRECTORY=/updater/data

      # Other
      - LOG_LEVEL=info
      - LOG_CALLER=hidden
      - SHOUTRRR_ADDRESSES=
    env_file:
      - path: ./tokens/sensitive-tokens.env
        required: true
    restart: always
