version: '3.8'

services:
  mc:
    image: itzg/minecraft-server:latest
    volumes:
    - ./modpacks:/modpacks:ro
    - data:/data
    environment:
      EULA: "true"
      TYPE: CURSEFORGE
      CF_SERVER_MOD: /modpacks/server_pack_for_real.zip
      MAX_MEMORY: 8G
    ports:
      - 25565:25565

volumes:
  data: {}
